#!/bin/bash

PATH=/opt/bin:$PATH
export PATH

shortopts="s:"
longopts="gid,key:,qsh,qsc:,csc:,pwr,sts,glg,jmp,jnt:,mnu"

gid=0; key=0; qsh=0; qsc=0; csc=0; pwr=0; sts=0; glg=0; jmp=0; jnt=0; mnu=0

temp=$(getopt -o $shortopts --long $longopts -n 'REMOTECONTROL' -- "$@")

#[ $? != 0 ] || ( echo "Terminating..." >&2 ; exit 1 )

eval set -- "$temp"

while true ; do
        case "$1" in
                -s) scannerindex=$2 ; shift 2 ;;
                --gid) gid=1; shift ;;
                --key) key=1; key_opts=$2; shift 2 ;;
                --qsh) qsh=1; qsh_opts=$2; shift 2 ;;
                --qsc) qsc=1; qsc_opts=$2; shift 2 ;;
                --csc) csc=1; csc_opts=$2; shift 2 ;;
                --pwr) pwr=1; shift ;;
                --sts) sts=1; shift ;;
                --glg) glg=1; shift ;;
                --jmp) jmp=1; jmp_opts=$2; shift 2 ;;
                --jnt) jnt=1; jnt_opts=$2; shift 2 ;;
                --mnu) mnu=1; mnu_opts=$2; shift 2 ;;
                --) shift ; break ;;
                *) echo "Internal error!" ; exit 1 ;;
        esac
done

test "X$scannerindex" == "X" && exit 1

readscanner="readscanner -d /dev/scanners/$scannerindex -s 50000"

[ "$gid" -eq 1 ] && ( echo $($readscanner -c GID); exit 0 )

[ "$key" -eq 1 ] && ( echo $($readscanner -c KEY,$key_opts); exit 0 )

[ "$qsh" -eq 1 ] && ( echo $($readscanner -c QSH,$qsh_opts); exit 0 )

[ "$qsc" -eq 1 ] && ( echo $($readscanner -c QSC,$qsc_opts); exit 0 )

[ "$csc" -eq 1 ] && ( echo $($readscanner -c CSC,$csc_opts); exit 0 )

[ "$pwr" -eq 1 ] && ( echo $($readscanner -c PWR); exit 0 )

[ "$sts" -eq 1 ] && ( echo $($readscanner -c STS); exit 0 )

[ "$glg" -eq 1 ] && ( echo $($readscanner -c GLG); exit 0 )

[ "$jmp" -eq 1 ] && ( echo $($readscanner -c JMP,$jmp_opts); exit 0 )

[ "$mnu" -eq 1 ] && ( echo $($readscanner -c MNU,$mnu_opts); exit 0 )
